
apiVersion: v1
data:
  appsettings_customersecret.json: 77u/ew0KICAgICJSYWJiaXRNUVB1Ymxpc2hlciI6IHsNCiAgICAgICAgIkhvc3QiOiAicnMtcm1xLW1ndC5uYXRnZW8uc3ZjLmNsdXN0ZXIubG9jYWwiLA0KICAgICAgICAiVXNlcm5hbWUiOiAiZ3Vlc3QiLA0KICAgICAgICAiUGFzc3dvcmQiOiAiZ3Vlc3QiLA0KICAgICAgIkV4Y2hhbmdlIjogIlBpdHN0b3AiDQogICAgfSwNCiAgICANCiAgICANCiAgICAiQ29ubmVjdGlvblN0cmluZ3MiOiB7DQogICAgICAiQ3VzdG9tZXJNYW5hZ2VtZW50Q04iOiAic2VydmVyPW1zc3FsLWRlcGxveW1lbnQubmF0Z2VvLnN2Yy5jbHVzdGVyLmxvY2FsO3VzZXIgaWQ9c2E7cGFzc3dvcmQ9TXlDMG05bCZ4UEBzc3cwcmQ7ZGF0YWJhc2U9Q3VzdG9tZXJNYW5hZ2VtZW50OyINCiAgICB9LA0KICAgIA0KICAgIA0KICAgICJTZXJpbG9nIjogew0KICAgICAgIlVzaW5nIjogWyAiU2VyaWxvZy5TaW5rcy5Db25zb2xlIiBdLA0KICAgICAgIk1pbmltdW1MZXZlbCI6ICJJbmZvcm1hdGlvbiIsDQogICAgICAiV3JpdGVUbyI6IFsNCiAgICAgICAgeyAiTmFtZSI6ICJDb25zb2xlIiB9LA0KICAgICAgICB7DQogICAgICAgICAgIk5hbWUiOiAiU2VxIiwNCiAgICAgICAgICAiQXJncyI6IHsgInNlcnZlclVybCI6ICJodHRwOi8vbG9nc2VydmVyOjUzNDEiIH0NCiAgICAgICAgfQ0KICAgICAgXSwNCiAgICAgICJQcm9wZXJ0aWVzIjogew0KICAgICAgICAiQXBwbGljYXRpb24iOiAiQ3VzdG9tZXJNYW5hZ2VtZW50QVBJIg0KICAgICAgfQ0KICAgIH0NCiAgfQ0KICA=
kind: Secret
metadata:
  name: settingscustomerapi-appsettings
  namespace: ##Namespace##
type: Opaque
