apiVersion: v1
data:
<<<<<<< HEAD
  SA_PASSWORD: TXlDMG05bCZ4UEBzc3cwcmQK            
=======
  SA_PASSWORD: TXlDMG05bCZ4UEBzc3cwcmQK
>>>>>>> 6816672803854ad756e1477d7d0421f724f20668
kind: Secret
metadata:
  name: mssql
  namespace: ##Namespace##
type: Opaque
